import { PathOps, cubic, line as lineSegment, uniformRadii } from '@leathercad/geometry';
import { describe, expect, it } from 'vitest';

import { evaluate, evaluationErrors, resolvedFeatures } from './evaluate.js';
import { DEFAULT_SETTINGS, type Feature, type Part, type Project } from './feature.js';

function panel(width = 105, height = 75): Feature {
  return {
    id: 'cut-1',
    kind: 'cut-contour',
    role: 'outer',
    name: 'Outline',
    visible: true,
    locked: false,
    source: {
      kind: 'shape',
      shape: {
        type: 'rect',
        origin: { x: 0, y: 0 },
        width,
        height,
        radii: uniformRadii(8),
        rotation: 0,
      },
    },
  };
}

function stitchLine(sourceId: string, distanceMm = 3.5, id = 'stitch-1'): Feature {
  return {
    id,
    kind: 'stitch-line',
    name: 'Stitch line',
    visible: true,
    locked: false,
    source: {
      kind: 'derived',
      sourceId,
      op: { type: 'offset', distanceMm, side: 'inward', run: { kind: 'whole' } },
    },
  };
}

function projectWith(features: Feature[]): Project {
  const part: Part = { id: 'part-1', name: 'Panel', quantity: 1, features };
  return { id: 'p', name: 'Test', settings: DEFAULT_SETTINGS, parts: [part] };
}

const lineIn = (project: Project, id = 'stitch-1'): number => {
  const found = [...resolvedFeatures(evaluate(project))].find((f) => f.feature.id === id);
  if (found === undefined) throw new Error(`${id} did not resolve`);
  return PathOps.length(found.path);
};

function holeSet(sourceId: string, pitchMm = 3.85): Feature {
  return {
    id: 'holes-1',
    kind: 'stitch-hole-set',
    name: 'Stitch holes',
    visible: true,
    locked: false,
    source: {
      kind: 'derived',
      sourceId,
      op: { type: 'stitch-holes', pitchMm, mode: 'fit-whole', corners: 'hole-at-corner' },
    },
  };
}

const holesIn = (project: Project) => {
  const found = [...resolvedFeatures(evaluate(project))].find((f) => f.feature.id === 'holes-1');
  if (found?.holes === undefined) throw new Error('holes did not resolve');
  return found.holes;
};

describe('the whole chain', () => {
  it('turns a dimensioned outline into holes on a stitch line', () => {
    const holes = holesIn(projectWith([panel(), stitchLine('cut-1'), holeSet('stitch-1')]));

    expect(holes.count).toBeGreaterThan(70);
    expect(holes.achievedPitchMm).toBeGreaterThan(3.5);
    expect(holes.achievedPitchMm).toBeLessThan(4.2);
  });

  it('regenerates every link when the source dimension changes', () => {
    // This is M3. Nothing is regenerated by hand; the width changes and the
    // holes follow.
    const narrow = holesIn(projectWith([panel(105), stitchLine('cut-1'), holeSet('stitch-1')]));
    const wide = holesIn(projectWith([panel(205), stitchLine('cut-1'), holeSet('stitch-1')]));

    expect(wide.count).toBeGreaterThan(narrow.count);
    // 200 mm more perimeter at ~3.85 mm is about 52 more holes.
    expect(wide.count - narrow.count).toBeGreaterThan(45);
    expect(wide.count - narrow.count).toBeLessThan(60);
  });

  it('changes the count when the pitch changes', () => {
    const coarse = holesIn(projectWith([panel(), stitchLine('cut-1'), holeSet('stitch-1', 5)]));
    const fine = holesIn(projectWith([panel(), stitchLine('cut-1'), holeSet('stitch-1', 2.7)]));

    expect(fine.count).toBeGreaterThan(coarse.count);
  });

  it('changes the count when the inset changes, because the run is shorter', () => {
    const near = holesIn(projectWith([panel(), stitchLine('cut-1', 3.5), holeSet('stitch-1')]));
    const deep = holesIn(projectWith([panel(), stitchLine('cut-1', 10), holeSet('stitch-1')]));

    expect(deep.count).toBeLessThan(near.count);
  });

  it('reports a hole set whose stitch line failed, without inventing holes', () => {
    const errors = evaluationErrors(
      evaluate(projectWith([panel(), stitchLine('cut-1', 60), holeSet('stitch-1')])),
    );

    expect(errors.some((e) => e.feature.id === 'holes-1')).toBe(true);
  });
});

describe('a derived stitch line', () => {
  it('follows its source inward by the inset', () => {
    // 105 x 75 with 8 mm corners, inset 3.5: the straights shorten by twice
    // the reduced radius, plus one circle of that radius.
    const expected = 2 * (98 - 9) + 2 * (68 - 9) + 2 * Math.PI * 4.5;
    expect(lineIn(projectWith([panel(), stitchLine('cut-1')]))).toBeCloseTo(expected, 6);
  });

  it('updates when the source changes even though its own object did not', () => {
    // The real editing path. The document is updated immutably with structural
    // sharing, so widening the panel replaces the cut contour object and
    // leaves the stitch line object *identical*. Caching on the feature alone
    // then returns the stitch line for the old outline, and the panel shows a
    // count that no longer matches the drawing.
    const line = stitchLine('cut-1');

    const before = lineIn(projectWith([panel(105), line]));
    const after = lineIn(projectWith([panel(205), line]));

    expect(after).toBeCloseTo(before + 200, 6);
  });

  it('updates when the source changes, with no explicit regenerate', () => {
    const narrow = lineIn(projectWith([panel(105), stitchLine('cut-1')]));
    const wide = lineIn(projectWith([panel(205), stitchLine('cut-1')]));

    expect(wide).toBeCloseTo(narrow + 200, 6);
  });

  it('reports one clear error when its source fails, not a cascade', () => {
    const broken: Feature = {
      ...panel(),
      source: {
        kind: 'shape',
        shape: {
          type: 'rect',
          origin: { x: 0, y: 0 },
          width: Number.NaN,
          height: 75,
          radii: uniformRadii(8),
          rotation: 0,
        },
      },
    };

    const errors = evaluationErrors(evaluate(projectWith([broken, stitchLine('cut-1')])));
    const onLine = errors.find((e) => e.feature.id === 'stitch-1');

    expect(onLine).toBeDefined();
    expect(onLine!.problem).toMatchObject({
      code: 'SOURCE_FAILED',
      facts: { featureId: 'stitch-1', sourceId: 'cut-1' },
    });
    // The root says what is actually wrong, naming the parameter the user typed.
    expect(errors.find((e) => e.feature.id === 'cut-1')?.problem).toMatchObject({
      code: 'PARAMETER_INVALID',
      facts: { parameter: 'width', requirement: 'finite' },
    });
  });

  it('reports a missing source rather than throwing', () => {
    const errors = evaluationErrors(evaluate(projectWith([stitchLine('does-not-exist')])));
    expect(errors[0]?.problem).toMatchObject({ code: 'SOURCE_MISSING' });
  });

  it('reports a cycle rather than recursing forever', () => {
    const a = stitchLine('stitch-2', 3.5, 'stitch-1');
    const b = stitchLine('stitch-1', 3.5, 'stitch-2');

    const errors = evaluationErrors(evaluate(projectWith([a, b])));
    expect(errors.map((e) => [e.feature.id, e.problem.code])).toEqual([
      ['stitch-1', 'CYCLE'],
      ['stitch-2', 'CYCLE'],
    ]);
  });

  it('refuses an inset deeper than the outline can hold, naming the problem', () => {
    const errors = evaluationErrors(evaluate(projectWith([panel(), stitchLine('cut-1', 60)])));
    expect(errors[0]?.problem).toMatchObject({
      code: 'OFFSET_COLLAPSED',
      facts: { distanceMm: 60, side: 'inward' },
    });
    // Pointing at the outline the inset could not fit inside.
    expect(errors[0]?.location?.kind).toBe('path');
  });

  it('reports an offset of a curve it cannot follow, rather than throwing', () => {
    const curvy: Feature = {
      ...panel(),
      source: {
        kind: 'path',
        path: PathOps.closed([
          cubic({ x: 0, y: 0 }, { x: 40, y: -20 }, { x: 80, y: 20 }, { x: 100, y: 0 }),
          lineSegment({ x: 100, y: 0 }, { x: 100, y: 60 }),
          lineSegment({ x: 100, y: 60 }, { x: 0, y: 60 }),
          lineSegment({ x: 0, y: 60 }, { x: 0, y: 0 }),
        ]),
      },
    };
    const errors = evaluationErrors(evaluate(projectWith([curvy, stitchLine('cut-1')])));
    expect(errors.map((e) => e.problem.code)).toEqual(['OFFSET_UNSUPPORTED']);
  });

  it('reports an unusable pitch by name instead of letting distribution throw', () => {
    const errors = evaluationErrors(
      evaluate(projectWith([panel(), stitchLine('cut-1'), holeSet('stitch-1', 0)])),
    );
    expect(errors[0]?.problem).toMatchObject({
      code: 'PARAMETER_INVALID',
      facts: { featureId: 'holes-1', parameter: 'pitch', requirement: 'positive', value: 0 },
    });
  });

  it('reports a negative inset by name', () => {
    const errors = evaluationErrors(evaluate(projectWith([panel(), stitchLine('cut-1', -2)])));
    expect(errors[0]?.problem).toMatchObject({
      code: 'PARAMETER_INVALID',
      facts: { parameter: 'inset', requirement: 'non-negative', value: -2 },
    });
  });

  it('finds a source in another part, since a seam spans two pieces', () => {
    const project: Project = {
      id: 'p',
      name: 'Test',
      settings: DEFAULT_SETTINGS,
      parts: [
        { id: 'part-1', name: 'A', quantity: 1, features: [panel()] },
        { id: 'part-2', name: 'B', quantity: 1, features: [stitchLine('cut-1')] },
      ],
    };

    expect(lineIn(project)).toBeGreaterThan(0);
  });
});
