import { type Mm } from '@leathercad/core';
import {
  MatOps,
  PathOps,
  cubic,
  line,
  quadraticToCubic,
  type Path,
  type Segment,
  type Vec2,
} from '@leathercad/geometry';

/**
 * The shape of the committed glyph data.
 *
 * Generated by `packages/typography/tools/generateGlyphs.mjs` from the
 * vendored typeface, at development time. **Nothing parses a font at run
 * time** (ADR 0011): what ships is outlines, in font units with Y up like
 * every other coordinate here.
 */
export interface GlyphData {
  /** Advance width, in font units. */
  readonly advance: number;
  /** Contours as `M`, `L`, `Q`, `C` and `Z` commands, in font units. */
  readonly d: string;
}

export interface FontData {
  readonly family: string;
  /** Which file this came from, so a regenerated set is traceable. */
  readonly source: string;
  readonly unitsPerEm: number;
  readonly ascender: number;
  readonly descender: number;
  readonly capHeight: number;
  readonly xHeight: number;
  /** The visible box drawn for a character the set does not cover. */
  readonly notdef: GlyphData;
  readonly glyphs: Readonly<Record<string, GlyphData>>;
  /** Kerning in font units, by left-hand character then right-hand character. */
  readonly kerning: Readonly<Record<string, Readonly<Record<string, number>>>>;
}

/**
 * A glyph's contours in font units, parsed once per character.
 *
 * Glyphs repeat constantly — every "mm" on every dimension — so parsing is
 * memoised on the glyph data object. The cache is keyed on identity, the same
 * trick `evaluate` uses.
 */
const contourCache = new WeakMap<GlyphData, readonly Path[]>();

export function contoursOf(glyph: GlyphData): readonly Path[] {
  const cached = contourCache.get(glyph);
  if (cached !== undefined) return cached;

  const contours = parseOutline(glyph.d);
  contourCache.set(glyph, contours);
  return contours;
}

/** Scales font-unit contours to millimetres and puts them where they belong. */
export function scaleContours(
  contours: readonly Path[],
  font: FontData,
  sizeMm: Mm,
  at: Vec2,
): Path[] {
  const scale = sizeMm / font.unitsPerEm;
  // A similarity, so any arc would stay an arc — glyphs hold only lines and
  // cubics, but the rule is the geometry layer's and not restated here.
  // Chronological: scale the font units down to millimetres, *then* move the
  // glyph to where it sits. The other order would scale the position too.
  const matrix = MatOps.compose(MatOps.fromScale(scale, scale), MatOps.fromTranslation(at));
  return contours.map((contour) => PathOps.transform(contour, matrix));
}

/**
 * Turns one glyph's command string into closed contours.
 *
 * Quadratics become cubics through the geometry layer's own conversion, which
 * is exact: a quadratic *is* a cubic with two of its control points placed two
 * thirds of the way along. The alternative — carrying a quadratic segment kind
 * through every backend — would put the same curve in two shapes.
 */
function parseOutline(d: string): readonly Path[] {
  if (d === '') return [];

  const contours: Path[] = [];
  let segments: Segment[] = [];
  let current: Vec2 = { x: 0, y: 0 };
  let start: Vec2 = { x: 0, y: 0 };

  // One pass, no regular expression backtracking: the data is machine-written
  // and every command is a letter followed by its numbers.
  const tokens = d.match(/[MLQCZ][^MLQCZ]*/g) ?? [];

  for (const token of tokens) {
    const command = token[0]!;
    const numbers = token
      .slice(1)
      .split(/[\s,]+/)
      .filter((part) => part !== '')
      .map(Number);

    switch (command) {
      case 'M':
        if (segments.length > 0) contours.push(PathOps.closed(segments));
        segments = [];
        current = { x: numbers[0]!, y: numbers[1]! };
        start = current;
        break;
      case 'L': {
        const to = { x: numbers[0]!, y: numbers[1]! };
        if (!samePoint(current, to)) segments.push(line(current, to));
        current = to;
        break;
      }
      case 'Q': {
        const control = { x: numbers[0]!, y: numbers[1]! };
        const to = { x: numbers[2]!, y: numbers[3]! };
        segments.push(quadraticToCubic(current, control, to));
        current = to;
        break;
      }
      case 'C': {
        const c1 = { x: numbers[0]!, y: numbers[1]! };
        const c2 = { x: numbers[2]!, y: numbers[3]! };
        const to = { x: numbers[4]!, y: numbers[5]! };
        segments.push(cubic(current, c1, c2, to));
        current = to;
        break;
      }
      case 'Z':
        // The closing line back to the contour's start is implied by `closed`,
        // so it is only emitted when the outline does not already end there.
        if (!samePoint(current, start)) segments.push(line(current, start));
        if (segments.length > 0) contours.push(PathOps.closed(segments));
        segments = [];
        current = start;
        break;
    }
  }

  if (segments.length > 0) contours.push(PathOps.closed(segments));
  return contours;
}

/** Font units are integers, so this is exact rather than a tolerance. */
function samePoint(a: Vec2, b: Vec2): boolean {
  return a.x === b.x && a.y === b.y;
}
