import type { Mm } from '@leathercad/core';

/**
 * Tick spacing for grids and rulers.
 *
 * Steps are always 1, 2 or 5 times a power of ten millimetres, so a gridline
 * always lands on a number a person would actually measure to. A step of 3 or
 * 7 mm is arithmetically fine and useless to read.
 */

/**
 * The smallest 1/2/5 step whose on-screen spacing is at least `minSpacingPx`.
 *
 * Driving this from a pixel spacing rather than a fixed millimetre value is
 * what makes the grid adaptive: zoom out and it thins to 10 mm, then 100 mm,
 * instead of collapsing into moiré.
 */
export function niceTickStepMm(minSpacingPx: number, pxPerMm: number): Mm {
  if (pxPerMm <= 0 || minSpacingPx <= 0) return 1;

  const minimumMm = minSpacingPx / pxPerMm;
  const exponent = Math.floor(Math.log10(minimumMm));
  const base = Math.pow(10, exponent);

  for (const multiple of [1, 2, 5]) {
    if (base * multiple >= minimumMm) return base * multiple;
  }
  return base * 10;
}

/**
 * The major step that goes with a minor one: the next whole power of ten.
 *
 * Major lines therefore always fall on 10, 100 or 1000 mm — the numbers a
 * ruler is labelled with — regardless of whether the minor step happens to be
 * 1, 2 or 5.
 */
export function majorStepFor(minorStepMm: Mm): Mm {
  if (minorStepMm <= 0) return 10;
  return Math.pow(10, Math.floor(Math.log10(minorStepMm)) + 1);
}

/**
 * Every multiple of `step` within `[min, max]`, ascending.
 *
 * Generated by index rather than by repeated addition, so floating-point error
 * cannot accumulate across a long span and leave a gridline a hair off.
 */
export function ticksInRange(min: Mm, max: Mm, step: Mm): Mm[] {
  if (step <= 0 || !Number.isFinite(min) || !Number.isFinite(max) || max < min) return [];

  const first = Math.ceil(min / step);
  const last = Math.floor(max / step);
  if (last < first) return [];

  // Guards against an accidental zoom state asking for millions of lines.
  const count = last - first + 1;
  if (count > 100_000) return [];

  const result: Mm[] = new Array<Mm>(count);
  for (let i = 0; i < count; i++) result[i] = (first + i) * step;
  return result;
}

/** Decimal places needed to label a tick of this size without noise. */
export function labelPrecisionFor(stepMm: Mm): number {
  if (stepMm >= 1) return 0;
  return Math.min(4, Math.ceil(-Math.log10(stepMm)));
}
