import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import {
  labelPrecisionFor,
  majorStepFor,
  niceTickStepMm,
  ticksInRange,
  labelStepFor,
} from './ticks.js';

describe('niceTickStepMm', () => {
  it('only ever returns 1, 2 or 5 times a power of ten', () => {
    // A step of 3 or 7 mm is arithmetically fine and useless to read.
    fc.assert(
      fc.property(
        fc.double({ min: 1, max: 200, noNaN: true }),
        fc.double({ min: 0.05, max: 400, noNaN: true }),
        (minSpacing, pxPerMm) => {
          const step = niceTickStepMm(minSpacing, pxPerMm);
          const mantissa = step / Math.pow(10, Math.floor(Math.log10(step)));
          return [1, 2, 5].some((m) => Math.abs(mantissa - m) < 1e-9);
        },
      ),
    );
  });

  it('always meets the requested minimum spacing', () => {
    fc.assert(
      fc.property(
        fc.double({ min: 1, max: 200, noNaN: true }),
        fc.double({ min: 0.05, max: 400, noNaN: true }),
        (minSpacing, pxPerMm) => niceTickStepMm(minSpacing, pxPerMm) * pxPerMm >= minSpacing - 1e-9,
      ),
    );
  });

  it('is the smallest such step, not merely a sufficient one', () => {
    fc.assert(
      fc.property(
        fc.double({ min: 1, max: 200, noNaN: true }),
        fc.double({ min: 0.05, max: 400, noNaN: true }),
        (minSpacing, pxPerMm) => {
          const step = niceTickStepMm(minSpacing, pxPerMm);
          const smaller = [1, 2, 5]
            .map((m) => m * Math.pow(10, Math.floor(Math.log10(step)) - (m === 5 ? 0 : 0)))
            .filter((s) => s < step);
          return smaller.every((s) => s * pxPerMm < minSpacing);
        },
      ),
    );
  });

  it('gives 1 mm at a comfortable zoom and coarsens as you zoom out', () => {
    expect(niceTickStepMm(8, 10)).toBe(1);
    expect(niceTickStepMm(8, 4)).toBe(2);
    expect(niceTickStepMm(8, 1)).toBe(10);
    expect(niceTickStepMm(8, 0.1)).toBe(100);
  });

  it('is monotonic: zooming out never gives a finer grid', () => {
    fc.assert(
      fc.property(
        fc.double({ min: 0.1, max: 100, noNaN: true }),
        fc.double({ min: 0.1, max: 100, noNaN: true }),
        (a, b) => {
          const [low, high] = a < b ? [a, b] : [b, a];
          return niceTickStepMm(8, low) >= niceTickStepMm(8, high);
        },
      ),
    );
  });

  it('degrades safely for nonsense input', () => {
    expect(niceTickStepMm(8, 0)).toBe(1);
    expect(niceTickStepMm(0, 10)).toBe(1);
  });
});

describe('majorStepFor', () => {
  it('lands on a power of ten whatever the minor step', () => {
    // A ruler is labelled 10, 100, 1000 — never 20 or 50.
    expect(majorStepFor(1)).toBe(10);
    expect(majorStepFor(2)).toBe(10);
    expect(majorStepFor(5)).toBe(10);
    expect(majorStepFor(10)).toBe(100);
    expect(majorStepFor(20)).toBe(100);
    expect(majorStepFor(50)).toBe(100);
  });

  it('is always larger than the minor step', () => {
    fc.assert(
      fc.property(
        fc.double({ min: 0.01, max: 1000, noNaN: true }),
        (minor) => majorStepFor(minor) > minor,
      ),
    );
  });
});

describe('ticksInRange', () => {
  it('covers the range and nothing outside it', () => {
    expect(ticksInRange(-5, 12, 5)).toEqual([-5, 0, 5, 10]);
  });

  it('every tick is an exact multiple of the step', () => {
    // Generated by index, not by repeated addition, so error cannot creep
    // across a long span and leave a gridline a hair off.
    fc.assert(
      fc.property(
        fc.double({ min: -1000, max: 0, noNaN: true }),
        fc.double({ min: 0, max: 1000, noNaN: true }),
        fc.constantFrom(0.1, 1, 2, 5, 10, 100),
        (min, max, step) =>
          ticksInRange(min, max, step).every((t) => {
            const multiple = t / step;
            return Math.abs(multiple - Math.round(multiple)) < 1e-9;
          }),
      ),
    );
  });

  it('is ascending', () => {
    fc.assert(
      fc.property(
        fc.double({ min: -500, max: 0, noNaN: true }),
        fc.double({ min: 0, max: 500, noNaN: true }),
        (min, max) => {
          const ticks = ticksInRange(min, max, 10);
          return ticks.every((t, i) => i === 0 || t > (ticks[i - 1] ?? t));
        },
      ),
    );
  });

  it('includes zero when the range straddles it', () => {
    expect(ticksInRange(-3, 3, 1)).toContain(0);
  });

  it('returns nothing for an empty or inverted range', () => {
    expect(ticksInRange(5, 1, 1)).toEqual([]);
    expect(ticksInRange(0, 10, 0)).toEqual([]);
  });

  it('refuses to generate an absurd number of lines', () => {
    // A bad zoom state must not lock the renderer up.
    expect(ticksInRange(-1e9, 1e9, 0.001)).toEqual([]);
  });
});

describe('labelPrecisionFor', () => {
  it('uses whole numbers for steps of 1 mm and up', () => {
    expect(labelPrecisionFor(1)).toBe(0);
    expect(labelPrecisionFor(10)).toBe(0);
  });

  it('adds decimals only when the step needs them', () => {
    expect(labelPrecisionFor(0.5)).toBe(1);
    expect(labelPrecisionFor(0.1)).toBe(1);
    expect(labelPrecisionFor(0.01)).toBe(2);
  });
});

describe('labelStepFor', () => {
  // F.5: labels went on every major tick, and zoomed out "−1200−1100−1000"
  // ran together on the top ruler. A label step leaves room for the label.
  const major = fc.constantFrom(0.1, 1, 10, 100, 1000);
  const pxPerMm = fc.double({ min: 0.05, max: 400, noNaN: true });
  const room = fc.double({ min: 5, max: 80, noNaN: true });

  it('labels only whole multiples of the major step', () => {
    fc.assert(
      fc.property(major, pxPerMm, room, (step, scale, needed) => {
        const label = labelStepFor(step, scale, needed);
        const multiple = label / step;
        return Math.abs(multiple - Math.round(multiple)) < 1e-9 && multiple >= 1;
      }),
    );
  });

  it('leaves at least the room a label needs', () => {
    fc.assert(
      fc.property(major, pxPerMm, room, (step, scale, needed) => {
        return labelStepFor(step, scale, needed) * scale >= needed - 1e-9;
      }),
    );
  });

  it('labels every major tick when there is room, and thins them only when there is not', () => {
    expect(labelStepFor(10, 4, 30)).toBe(10); // 40 px apart: every one
    expect(labelStepFor(100, 0.2, 40)).toBe(200); // 20 px apart: every other one
    expect(labelStepFor(100, 0.2, 90)).toBe(500);
  });
});
