import type { Mm } from '@leathercad/core';

/**
 * Tick spacing for grids and rulers.
 *
 * Steps are always 1, 2 or 5 times a power of ten millimetres, so a gridline
 * always lands on a number a person would actually measure to. A step of 3 or
 * 7 mm is arithmetically fine and useless to read.
 */

/**
 * The smallest 1/2/5 step whose on-screen spacing is at least `minSpacingPx`.
 *
 * Driving this from a pixel spacing rather than a fixed millimetre value is
 * what makes the grid adaptive: zoom out and it thins to 10 mm, then 100 mm,
 * instead of collapsing into moiré.
 */
export function niceTickStepMm(minSpacingPx: number, pxPerMm: number): Mm {
  if (pxPerMm <= 0 || minSpacingPx <= 0) return 1;

  const minimumMm = minSpacingPx / pxPerMm;
  const exponent = Math.floor(Math.log10(minimumMm));
  const base = Math.pow(10, exponent);

  // Compared in pixels, as the spacing is asked for — not against
  // `minimumMm`, whose division can round up past a step that meets it
  // exactly: 1.0000000000000004 px at 0.05000000000000002 px/mm needs 20 mm,
  // which the quotient made look 4e-15 mm too short, and 50 came back.
  for (const multiple of [1, 2, 5]) {
    if (base * multiple * pxPerMm >= minSpacingPx) return base * multiple;
  }
  return base * 10;
}

/**
 * The major step that goes with a minor one: the next whole power of ten.
 *
 * Major lines therefore always fall on 10, 100 or 1000 mm — the numbers a
 * ruler is labelled with — regardless of whether the minor step happens to be
 * 1, 2 or 5.
 */
export function majorStepFor(minorStepMm: Mm): Mm {
  if (minorStepMm <= 0) return 10;
  return Math.pow(10, Math.floor(Math.log10(minorStepMm)) + 1);
}

/**
 * Every multiple of `step` within `[min, max]`, ascending.
 *
 * Generated by index rather than by repeated addition, so floating-point error
 * cannot accumulate across a long span and leave a gridline a hair off.
 */
export function ticksInRange(min: Mm, max: Mm, step: Mm): Mm[] {
  if (step <= 0 || !Number.isFinite(min) || !Number.isFinite(max) || max < min) return [];

  const first = Math.ceil(min / step);
  const last = Math.floor(max / step);
  if (last < first) return [];

  // Guards against an accidental zoom state asking for millions of lines.
  const count = last - first + 1;
  if (count > 100_000) return [];

  const result: Mm[] = new Array<Mm>(count);
  for (let i = 0; i < count; i++) result[i] = (first + i) * step;
  return result;
}

/** Decimal places needed to label a tick of this size without noise. */
export function labelPrecisionFor(stepMm: Mm): number {
  if (stepMm >= 1) return 0;
  return Math.min(4, Math.ceil(-Math.log10(stepMm)));
}

/**
 * How often to label a ruler: the smallest 1-2-5 multiple of the major step
 * that leaves `roomPx` between labels (F.5).
 *
 * Every major tick used to carry a label, so zoomed out the top ruler's
 * figures ran into one another. Ticks stay where they are; only the labels
 * thin, and always onto major ticks, so a label never names a minor one.
 */
export function labelStepFor(majorStepMm: Mm, pxPerMm: number, roomPx: number): Mm {
  if (majorStepMm <= 0 || pxPerMm <= 0) return majorStepMm;
  for (let decade = 1; ; decade *= 10) {
    for (const multiple of [1, 2, 5]) {
      const step = majorStepMm * multiple * decade;
      if (step * pxPerMm >= roomPx) return step;
    }
  }
}
